/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedBankRouteImport } from './routes/_authenticated/bank'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKelasRouteImport } from './routes/_authenticated/kelas'
import { Route as AuthenticatedKurikulumRouteImport } from './routes/_authenticated/kurikulum'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedPenilaianRouteImport } from './routes/_authenticated/penilaian'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams.index'
import { Route as AuthenticatedUjianIndexRouteImport } from './routes/_authenticated/ujian.index'
import { Route as AuthenticatedUjianExamIdRouteImport } from './routes/_authenticated/ujian.$examId'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'
import { Route as ApiPublicSeedDemoClassesRouteImport } from './routes/api/public/seed-demo-classes'
import { Route as ApiPublicSeedDemoDataRouteImport } from './routes/api/public/seed-demo-data'
import { Route as ApiPublicSeedDemoStudentsRouteImport } from './routes/api/public/seed-demo-students'
import { Route as AuthenticatedExamsExamIdIndexRouteImport } from './routes/_authenticated/exams.$examId.index'
import { Route as AuthenticatedExamsExamIdHasilRouteImport } from './routes/_authenticated/exams.$examId.hasil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankRoute = AuthenticatedBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKelasRoute = AuthenticatedKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKurikulumRoute = AuthenticatedKurikulumRouteImport.update({
  id: '/kurikulum',
  path: '/kurikulum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenilaianRoute = AuthenticatedPenilaianRouteImport.update({
  id: '/penilaian',
  path: '/penilaian',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUjianIndexRoute = AuthenticatedUjianIndexRouteImport.update({
  id: '/ujian/',
  path: '/ujian/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUjianExamIdRoute =
  AuthenticatedUjianExamIdRouteImport.update({
    id: '/ujian/$examId',
    path: '/ujian/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemoClassesRoute =
  ApiPublicSeedDemoClassesRouteImport.update({
    id: '/api/public/seed-demo-classes',
    path: '/api/public/seed-demo-classes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSeedDemoDataRoute = ApiPublicSeedDemoDataRouteImport.update({
  id: '/api/public/seed-demo-data',
  path: '/api/public/seed-demo-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemoStudentsRoute =
  ApiPublicSeedDemoStudentsRouteImport.update({
    id: '/api/public/seed-demo-students',
    path: '/api/public/seed-demo-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedExamsExamIdIndexRoute =
  AuthenticatedExamsExamIdIndexRouteImport.update({
    id: '/exams/$examId/',
    path: '/exams/$examId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsExamIdHasilRoute =
  AuthenticatedExamsExamIdHasilRouteImport.update({
    id: '/exams/$examId/hasil',
    path: '/exams/$examId/hasil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/bank': typeof AuthenticatedBankRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kelas': typeof AuthenticatedKelasRoute
  '/kurikulum': typeof AuthenticatedKurikulumRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/penilaian': typeof AuthenticatedPenilaianRoute
  '/ujian/$examId': typeof AuthenticatedUjianExamIdRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/seed-demo-classes': typeof ApiPublicSeedDemoClassesRoute
  '/api/public/seed-demo-data': typeof ApiPublicSeedDemoDataRoute
  '/api/public/seed-demo-students': typeof ApiPublicSeedDemoStudentsRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/ujian/': typeof AuthenticatedUjianIndexRoute
  '/exams/$examId/hasil': typeof AuthenticatedExamsExamIdHasilRoute
  '/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/bank': typeof AuthenticatedBankRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kelas': typeof AuthenticatedKelasRoute
  '/kurikulum': typeof AuthenticatedKurikulumRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/penilaian': typeof AuthenticatedPenilaianRoute
  '/ujian/$examId': typeof AuthenticatedUjianExamIdRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/seed-demo-classes': typeof ApiPublicSeedDemoClassesRoute
  '/api/public/seed-demo-data': typeof ApiPublicSeedDemoDataRoute
  '/api/public/seed-demo-students': typeof ApiPublicSeedDemoStudentsRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/ujian': typeof AuthenticatedUjianIndexRoute
  '/exams/$examId/hasil': typeof AuthenticatedExamsExamIdHasilRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/bank': typeof AuthenticatedBankRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kelas': typeof AuthenticatedKelasRoute
  '/_authenticated/kurikulum': typeof AuthenticatedKurikulumRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/penilaian': typeof AuthenticatedPenilaianRoute
  '/_authenticated/ujian/$examId': typeof AuthenticatedUjianExamIdRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/seed-demo-classes': typeof ApiPublicSeedDemoClassesRoute
  '/api/public/seed-demo-data': typeof ApiPublicSeedDemoDataRoute
  '/api/public/seed-demo-students': typeof ApiPublicSeedDemoStudentsRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/ujian/': typeof AuthenticatedUjianIndexRoute
  '/_authenticated/exams/$examId/hasil': typeof AuthenticatedExamsExamIdHasilRoute
  '/_authenticated/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/backup'
    | '/bank'
    | '/dashboard'
    | '/kelas'
    | '/kurikulum'
    | '/pengguna'
    | '/penilaian'
    | '/ujian/$examId'
    | '/api/public/seed-demo'
    | '/api/public/seed-demo-classes'
    | '/api/public/seed-demo-data'
    | '/api/public/seed-demo-students'
    | '/exams/'
    | '/ujian/'
    | '/exams/$examId/hasil'
    | '/exams/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/backup'
    | '/bank'
    | '/dashboard'
    | '/kelas'
    | '/kurikulum'
    | '/pengguna'
    | '/penilaian'
    | '/ujian/$examId'
    | '/api/public/seed-demo'
    | '/api/public/seed-demo-classes'
    | '/api/public/seed-demo-data'
    | '/api/public/seed-demo-students'
    | '/exams'
    | '/ujian'
    | '/exams/$examId/hasil'
    | '/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/backup'
    | '/_authenticated/bank'
    | '/_authenticated/dashboard'
    | '/_authenticated/kelas'
    | '/_authenticated/kurikulum'
    | '/_authenticated/pengguna'
    | '/_authenticated/penilaian'
    | '/_authenticated/ujian/$examId'
    | '/api/public/seed-demo'
    | '/api/public/seed-demo-classes'
    | '/api/public/seed-demo-data'
    | '/api/public/seed-demo-students'
    | '/_authenticated/exams/'
    | '/_authenticated/ujian/'
    | '/_authenticated/exams/$examId/hasil'
    | '/_authenticated/exams/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  ApiPublicSeedDemoClassesRoute: typeof ApiPublicSeedDemoClassesRoute
  ApiPublicSeedDemoDataRoute: typeof ApiPublicSeedDemoDataRoute
  ApiPublicSeedDemoStudentsRoute: typeof ApiPublicSeedDemoStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank': {
      id: '/_authenticated/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AuthenticatedBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kelas': {
      id: '/_authenticated/kelas'
      path: '/kelas'
      fullPath: '/kelas'
      preLoaderRoute: typeof AuthenticatedKelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kurikulum': {
      id: '/_authenticated/kurikulum'
      path: '/kurikulum'
      fullPath: '/kurikulum'
      preLoaderRoute: typeof AuthenticatedKurikulumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penilaian': {
      id: '/_authenticated/penilaian'
      path: '/penilaian'
      fullPath: '/penilaian'
      preLoaderRoute: typeof AuthenticatedPenilaianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ujian/': {
      id: '/_authenticated/ujian/'
      path: '/ujian'
      fullPath: '/ujian/'
      preLoaderRoute: typeof AuthenticatedUjianIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ujian/$examId': {
      id: '/_authenticated/ujian/$examId'
      path: '/ujian/$examId'
      fullPath: '/ujian/$examId'
      preLoaderRoute: typeof AuthenticatedUjianExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo-classes': {
      id: '/api/public/seed-demo-classes'
      path: '/api/public/seed-demo-classes'
      fullPath: '/api/public/seed-demo-classes'
      preLoaderRoute: typeof ApiPublicSeedDemoClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo-data': {
      id: '/api/public/seed-demo-data'
      path: '/api/public/seed-demo-data'
      fullPath: '/api/public/seed-demo-data'
      preLoaderRoute: typeof ApiPublicSeedDemoDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo-students': {
      id: '/api/public/seed-demo-students'
      path: '/api/public/seed-demo-students'
      fullPath: '/api/public/seed-demo-students'
      preLoaderRoute: typeof ApiPublicSeedDemoStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exams/$examId/': {
      id: '/_authenticated/exams/$examId/'
      path: '/exams/$examId'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId/hasil': {
      id: '/_authenticated/exams/$examId/hasil'
      path: '/exams/$examId/hasil'
      fullPath: '/exams/$examId/hasil'
      preLoaderRoute: typeof AuthenticatedExamsExamIdHasilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedBankRoute: typeof AuthenticatedBankRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKelasRoute: typeof AuthenticatedKelasRoute
  AuthenticatedKurikulumRoute: typeof AuthenticatedKurikulumRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedPenilaianRoute: typeof AuthenticatedPenilaianRoute
  AuthenticatedUjianExamIdRoute: typeof AuthenticatedUjianExamIdRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedUjianIndexRoute: typeof AuthenticatedUjianIndexRoute
  AuthenticatedExamsExamIdHasilRoute: typeof AuthenticatedExamsExamIdHasilRoute
  AuthenticatedExamsExamIdIndexRoute: typeof AuthenticatedExamsExamIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedBankRoute: AuthenticatedBankRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKelasRoute: AuthenticatedKelasRoute,
  AuthenticatedKurikulumRoute: AuthenticatedKurikulumRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedPenilaianRoute: AuthenticatedPenilaianRoute,
  AuthenticatedUjianExamIdRoute: AuthenticatedUjianExamIdRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedUjianIndexRoute: AuthenticatedUjianIndexRoute,
  AuthenticatedExamsExamIdHasilRoute: AuthenticatedExamsExamIdHasilRoute,
  AuthenticatedExamsExamIdIndexRoute: AuthenticatedExamsExamIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  ApiPublicSeedDemoClassesRoute: ApiPublicSeedDemoClassesRoute,
  ApiPublicSeedDemoDataRoute: ApiPublicSeedDemoDataRoute,
  ApiPublicSeedDemoStudentsRoute: ApiPublicSeedDemoStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
